name: Deploy Portfolio Website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Setup AWS SAM
      uses: aws-actions/setup-sam@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: SAM Build
      run: sam build

    - name: SAM Deploy
      run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset

    - name: Get API Gateway URL
      id: get-api-url
      run: |
        API_URL=$(aws cloudformation describe-stacks --stack-name portfolio-website-stack --query 'Stacks[0].Outputs[?OutputKey==`ApiGatewayUrl`].OutputValue' --output text)
        echo "api_url=$API_URL" >> $GITHUB_OUTPUT

    - name: Update JavaScript with API URL
      run: |
        sed -i "s|API_GATEWAY_URL_PLACEHOLDER|${{ steps.get-api-url.outputs.api_url }}|g" website/app.js

    - name: Deploy Website to S3
      run: |
        aws s3 sync website/ s3://bitirmeproject/ --delete
        
    - name: Invalidate CloudFront (Optional)
      run: |
        echo "CloudFront invalidation can be added here if needed"